### ISSUE TITLE
Linux support: module 'subprocess' has no attribute 'STARTUPINFO'

### ISSUE THREAD

**Issue by plutext** [tombrennan06/qgis-nsw-topo#3]
```
>>> exec(compile(Path('/tmp/tmpsbkuld2x').read_text(), 'Untitled-1', 'exec'))
Traceback (most recent call last):
  File "/usr/lib/python3.12/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "Untitled-1", line 392, in <module>
  File "Untitled-0", line 96, in addArcGisLayer
AttributeError: module 'subprocess' has no attribute 'STARTUPINFO'
```
STARTUPINFO is apparently a Windows thing; I'm trying to run the script on Linux.

Things work for me if I edit the addArcGisLayer.py  script, as follows:
```
        #si = subprocess.STARTUPINFO()
        #si.dwFlags |= subprocess.STARTF_USESHOWWINDOW
        subprocess.run(cmd, shell=True)
```

**Comment by tombrennan06** [comment]
Do you want to create a pull request for this change? It looks like it will work on both Windows and Linux.
